[tool.poetry]
name = "crmtgbot"
version = "0.1.0"
description = ""
authors = ["Arthur <baginian.artur@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
aiogram = "^3.15.0"
pydantic-settings = "^2.6.1"
retailcrm = "^5.1.2"
dishka = "^1.4.2"

[tool.black]
line-length = 120
target-version = ['py312']

[tool.isort]
line_length = 120
atomic = true
include_trailing_comma = true
use_parentheses = true
profile = "black"
lines_before_imports = 1
lines_after_imports = 2
combine_as_imports = true
multi_line_output = 3

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
