services:
  app:
    image: &app_image ghcr.io/haykor/crm_tgbot:latest

    restart: unless-stopped

    env_file:
      - .env

    depends_on:
      redis:
        condition: service_healthy

    healthcheck: &service_healthcheck
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 2s
      start_interval: 1s

    ports:
      - 8000:8000

  redis:
    image: redis:7-alpine

    restart: unless-stopped

    healthcheck:
      <<: *service_healthcheck
      test: ["CMD", "redis-cli", "ping"]
      start_period: 1s
      start_interval: 1s
